# Generated by Django 4.2.7 on 2024-05-25 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('wallet_type', models.CharField(blank=True, choices=[('USDT', 'USDT'), ('LTC', 'Litecoin'), ('BTC', 'Bitcoin'), ('XRP', 'XRP'), ('ETH', 'ETHERUM')], max_length=10, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=100, null=True)),
                ('usdt_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
