# Generated by Django 5.0.6 on 2024-05-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_country_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
