# Generated by Django 4.2.7 on 2024-06-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('acct_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='1', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('litecoin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('xrp_address', models.CharField(blank=True, max_length=200, null=True)),
                ('etherum_address', models.CharField(blank=True, max_length=200, null=True)),
                ('usdt_address', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(default='Wallet Address', max_length=100)),
            ],
        ),
    ]
