# Generated by Django 4.2 on 2024-09-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(choices=[('Term 1', 'Term 1: $50,000 to $500,000'), ('Term 2', 'Term 2: $1,000,000 or more')], max_length=50)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_rate_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('repayment_term_min', models.IntegerField(help_text='Minimum repayment term in months')),
                ('repayment_term_max', models.IntegerField(help_text='Maximum repayment term in months')),
                ('repayment_frequency', models.CharField(default='Monthly', max_length=50)),
                ('origination_fee_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('origination_fee_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('late_payment_fee_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('late_payment_fee_fixed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prepayment_penalty', models.BooleanField(default=False)),
                ('default_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collateral_required', models.BooleanField(default=False)),
                ('credit_score_min', models.IntegerField()),
                ('income_requirement_personal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_requirement_business', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_to_income_ratio_max', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
