# Generated by Django 4.2 on 2024-09-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='upfront',
            name='loan_amount_requested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
