# Generated by Django 4.2 on 2024-09-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_loanapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='date_applied',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='amount_requested',
            new_name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='approved',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
