# Generated by Django 5.0.6 on 2024-10-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_rename_date_applied_loanapplication_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanterm',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
