# Generated by Django 4.2.4 on 2023-12-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='referral_bonus',
            field=models.PositiveBigIntegerField(blank=True, default=10, null=True),
        ),
    ]
