# Generated by Django 4.2.4 on 2024-01-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_website_referral_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='referral_bonus',
        ),
    ]
