# Generated by Django 5.0.6 on 2024-06-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_rename_referral_profit_referral_referral_bonus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
