# Generated by Django 4.2.7 on 2024-05-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_email_verified'),
        ('accounts', '0002_customuser_email_verified_and_more'),
    ]

    operations = [
    ]
