# Generated by Django 4.2.7 on 2024-05-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_image'),
        ('accounts', '0004_customuser_referral'),
    ]

    operations = [
    ]
