# Generated by Django 5.0.6 on 2024-05-31 19:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=1, upload_to=accounts.models.profile_image_path),
            preserve_default=False,
        ),
    ]
