# Generated by Django 5.0.6 on 2024-05-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0006_withdrawalsmade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalsmade',
            name='message',
        ),
        migrations.RemoveField(
            model_name='withdrawalsmade',
            name='status',
        ),
        migrations.AddField(
            model_name='withdrawalsmade',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
