# Generated by Django 5.0.6 on 2024-05-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0007_remove_withdrawalsmade_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsmade',
            name='message',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
