# Generated by Django 5.0.6 on 2024-05-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0008_withdrawalsmade_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
