# Generated by Django 5.0.6 on 2024-05-31 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0009_delete_withdrawal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
