# Generated by Django 4.2.7 on 2024-05-31 16:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolioadd_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioadd',
            name='min_invest',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioadd',
            name='port_returns1',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioadd',
            name='port_returns2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioadd',
            name='port_returns3',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioadd',
            name='port_returns4',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioadd',
            name='port_weight1',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioadd',
            name='port_weight2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioadd',
            name='port_weight3',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioadd',
            name='port_weight4',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
    ]
