# Generated by Django 4.2.7 on 2024-05-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolioadd_min_invest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioadd',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
