# Generated by Django 4.2.7 on 2024-05-31 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolioadd_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='staamounttus',
            new_name='status',
        ),
    ]
