# Generated by Django 5.0.6 on 2024-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='recipient_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
