# Generated by Django 4.2 on 2024-09-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
